export interface BaselineCaseStudy {
  id: string;
  slug: string;
  clientName: string;
  industry: string;
  headline: string;
  metric: string;
  problem: string;
  strategy: string;
  contentCreated: string;
  shoots: string;
  influencerMarketing: string;
  ads: string;
  results: string;
  testimonialQuote: string;
  testimonialAuthor: string;
  testimonialRole: string;
  imageUrl?: string;
  videoUrl?: string;
  isLocked: boolean;
}

export const baselineCaseStudies: BaselineCaseStudy[] = [
  {
    id: 'locked-real-1',
    slug: 'shree-mahalaxmi',
    clientName: 'Shree Mahalaxmi Jewellers',
    industry: 'Jewellery & Luxury',
    headline: 'One store became three. Small pages became a 36K+ combined audience.',
    metric: '36K+ Audience Growth',
    problem: 'Each store page had only 500 to 1,000 followers and relied on passive footfall without any active social media brand presence.',
    strategy: 'Rebuilt social media strategy around jewellery collections, festival campaigns, founder & staff content, vertical Reels, and Meta Ads.',
    contentCreated: 'High-converting vertical Reels and collection launch assets.',
    shoots: 'On-location store and collection shoots.',
    influencerMarketing: 'Targeted local influencer amplification.',
    ads: 'Meta Ads for key collection launches.',
    results: 'Expanded to 3 stores, growing pages to 15K+ (Kurla), 12K+ (Chembur), and 9K+ (Mahalaxmi) — creating 36K+ combined followers and continuous footfall.',
    testimonialQuote: 'The goal was never only to make the Instagram pages bigger. The bigger goal was to use social media to help make the businesses bigger.',
    testimonialAuthor: 'Shree Mahalaxmi Owner',
    testimonialRole: 'Jewellery Business Owner',
    imageUrl: '/vedios/business client testimonial/Video-37410_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-37410.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-2',
    slug: 'hazel-dryfruit',
    clientName: 'Hazel Dryfruit & Sweets',
    industry: 'F&B & Festive',
    headline: 'The campaign where the owner asked us to stop boosting.',
    metric: '+240% Festive Sales Uplift',
    problem: 'Reaching local buyers outside Mumbai and converting digital views into physical store visits during peak Raksha Bandhan festival window.',
    strategy: 'Arranged local production team, festive concept scripts with owner, coordinated shoots, influencer marketing, and hyper-targeted Meta Ads.',
    contentCreated: 'Festive concept Reels & gift unboxing content.',
    shoots: 'Local festive product & store shoots.',
    influencerMarketing: 'Local foodie & lifestyle influencer collaborations.',
    ads: 'Local footfall targeted Meta Ads.',
    results: 'Overcrowded store 1 day before Raksha Bandhan, prompting owner to request pausing ads due to extreme customer volume.',
    testimonialQuote: 'Stop boosting. It\'s overcrowded.',
    testimonialAuthor: 'Hazel Sweets Owner',
    testimonialRole: 'F&B Retail Owner',
    imageUrl: '/vedios/business client testimonial/Video-4099_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-4099.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-3',
    slug: 'raj-laxmi',
    clientName: 'Raj Laxmi Jewellers',
    industry: 'Jewellery & Luxury',
    headline: 'A struggling page. Then 300K+ views on the first business reel.',
    metric: '300K+ Views on 1st Reel',
    problem: 'Generating organic reach in a competitive jewellery niche while operating outside Mumbai with a struggling Instagram page.',
    strategy: 'Arranged local videography, studied customer profile, developed customized content concepts and hook-first reels with high-retention editing.',
    contentCreated: 'Hook-first vertical video reels and collection highlights.',
    shoots: 'Local videography at client showroom.',
    influencerMarketing: 'Niche jewellery creator tagging.',
    ads: 'Engagement boost campaigns.',
    results: 'First new business reel crossed 300,000+ views, instantly transforming page reach and customer engagement.',
    testimonialQuote: 'The first result showed us what our page could achieve with structured hooks and execution.',
    testimonialAuthor: 'Raj Laxmi Owner',
    testimonialRole: 'Jewellery Store Owner',
    imageUrl: '/vedios/business client testimonial/Video-41182_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-41182.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-4',
    slug: 'devi-company',
    clientName: 'Devi & Company, Kanpur',
    industry: 'Fashion & Retail',
    headline: 'Two established stores. A third store opening. A new campaign underway.',
    metric: '3rd Store Grand Opening',
    problem: 'Launching their 3rd store in Kanpur with maximum local awareness and driving heavy footfall on opening week.',
    strategy: 'Built store launch strategy, planned promotional creatives & offer communication, executed digital distribution and targeted campaign marketing across Kanpur.',
    contentCreated: 'Grand opening promo reels and collection lookbooks.',
    shoots: 'Store opening coverage and model lookbook shoots.',
    influencerMarketing: 'Kanpur city fashion creators.',
    ads: 'Geo-targeted city awareness Meta Ads.',
    results: 'Successfully established launch momentum and built massive digital buzz across Kanpur for the new store opening.',
    testimonialQuote: 'Famebros Studio gave our 3rd store opening the exact buzz and footfall we needed.',
    testimonialAuthor: 'Devi & Co Team',
    testimonialRole: 'Fashion Retail Founder',
    imageUrl: '/vedios/business client testimonial/Video-58243_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-58243.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-5',
    slug: 'ali-salon',
    clientName: 'Ali Salon',
    industry: 'Salon & Services',
    headline: '25 Years in business. No social presence. 10X more inquiries with us.',
    metric: '10X Booking Inquiries',
    problem: '25 years of local goodwill but zero active social media presence or digital booking system.',
    strategy: 'Captured transformation reels, produced authentic founder & stylist videos explaining hair care, optimized Instagram DMs and WhatsApp routing for direct booking.',
    contentCreated: 'Stylist transformations and client hair care reels.',
    shoots: 'In-salon styling and transformation shoots.',
    influencerMarketing: 'Local salon guest collaborations.',
    ads: 'Hyper-local city grooming ad campaigns.',
    results: 'Generated 10X more customer inquiries per month, attracting new clients from across the city.',
    testimonialQuote: 'After 25 years of word of mouth, Famebros Studio brought us a whole new stream of younger customers.',
    testimonialAuthor: 'Ali Salon Founder',
    testimonialRole: 'Salon Business Owner',
    imageUrl: '/vedios/business client testimonial/Video-60156_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-60156.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-6',
    slug: 'sk-furniture',
    clientName: 'SK Furniture',
    industry: 'Fashion & Retail',
    headline: '10K+ followers in 6 months + customer queues despite an offbeat location.',
    metric: '10K+ Followers in 6 Months',
    problem: 'Offbeat market location with slow footfall, dependent heavily on word-of-mouth.',
    strategy: 'Filmed showroom walkthroughs, durability tests, pricing transparency reels, localized video campaigns highlighting unique designs.',
    contentCreated: 'Showroom walkthroughs and product durability test reels.',
    shoots: 'Showroom video production sessions.',
    influencerMarketing: 'Home decor creators.',
    ads: 'Local furniture buyer targeted Meta Ads.',
    results: 'Grew to 10K+ followers in 6 months, creating regular customer queues inside the store despite offbeat location.',
    testimonialQuote: 'Customers now travel directly to our showroom after seeing our reels.',
    testimonialAuthor: 'SK Furniture Owner',
    testimonialRole: 'Furniture Business Owner',
    imageUrl: '/vedios/business client testimonial/Video-68531_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-68531.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-7',
    slug: 'arabian-collection',
    clientName: 'Arabian Collection',
    industry: 'Fashion & Retail',
    headline: '600K+ Followers | Mumbai, Dubai & Hyderabad | 3 Years With Us.',
    metric: '600K+ Followers Across Brands',
    problem: 'Maintaining premium brand consistency and high content standards across international branches (Mumbai, Dubai, Hyderabad).',
    strategy: 'Produced high-production luxury reels and fabric detail videos, managed ongoing branding, campaign shoots, and influencer collaborations across 3 years.',
    contentCreated: 'Luxury ethnic wear reels and couture launch films.',
    shoots: 'Multi-city high-end fashion shoots.',
    influencerMarketing: 'Pan-India and UAE fashion influencers.',
    ads: 'High-ROI luxury fashion Meta Ads.',
    results: 'Crossed 600,000+ combined followers across accounts, establishing brand authority in India & UAE.',
    testimonialQuote: '3 years of continuous growth with Famebros Studio elevated our brand to an international level.',
    testimonialAuthor: 'Arabian Collection Management',
    testimonialRole: 'Brand Director',
    imageUrl: '/vedios/business client testimonial/Video-71170_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-71170.mp4',
    isLocked: true,
  },
  {
    id: 'locked-real-8',
    slug: 'al-ahmed',
    clientName: 'Al Ahmed Perfumes',
    industry: 'D2C Brands',
    headline: 'India\'s Top Perfume Brand | 3 Years With Us.',
    metric: 'Top Attar & Perfume Brand',
    problem: 'Conveying fragrance notes, luxury packaging, and brand prestige through digital video content.',
    strategy: 'Shot cinematic product films, fragrance breakdown reels, founder-led storytelling highlighting traditional perfume craft, monthly campaigns.',
    contentCreated: 'Cinematic fragrance reels and founder craft stories.',
    shoots: 'Product cinematography & luxury packaging shoots.',
    influencerMarketing: 'Top lifestyle and fragrance reviewers.',
    ads: 'E-commerce conversion & D2C Meta Ads.',
    results: 'Maintained a 3-year continuous growth partnership, strengthening Al Ahmed\'s position as India\'s top perfume brand.',
    testimonialQuote: 'Famebros Studio helped us build the online presence that made us India\'s top perfume brand.',
    testimonialAuthor: 'Al Ahmed Perfumes Founder',
    testimonialRole: 'D2C Brand Founder',
    imageUrl: '/vedios/business client testimonial/Video-74493_poster.jpg',
    videoUrl: '/vedios/business client testimonial/Video-74493.mp4',
    isLocked: true,
  },
];
